language: node_js
node_js:
  - 12.20.2
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17.3
  - export PATH="$HOME/.yarn/bin:$PATH"
  - echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc
  - yarn add global truffle
script:
  - echo 'Build starts!!'
  - echo 'Installing Deps!'
  - yarn
  - echo 'Testing!'
  - yarn build:contract
  - yarn test
  # - yarn deploy:contract
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: solidity-truffle-ui-app